"""Generate Markdown reports from assessment results."""
from __future__ import annotations

import logging
from typing import Optional

from .models import AssessmentResult, Finding, Severity

log = logging.getLogger(__name__)


def _severity_section(severity: Severity) -> str:
    icons = {
        Severity.CRITICAL: "🔴",
        Severity.WARNING: "⚠️",
        Severity.INFO: "ℹ️",
        Severity.OK: "✅",
    }
    return f"{icons.get(severity, '')} {severity.value.capitalize()} Findings"


def _finding_block(f: Finding) -> str:
    lines = [
        f"### {f.title}",
        "",
        f"**Category:** {f.category}  ",
        f"**Severity:** {f.severity.label}  ",
        "",
        f"**Description:** {f.description}",
        "",
        f"**Impact:** {f.impact}",
        "",
        f"**Remediation:** {f.remediation}",
    ]
    if f.az_command:
        lines += ["", "**CLI Command:**", f"```bash\n{f.az_command}\n```"]
    if f.doc_url:
        lines += ["", f"📖 [Documentation]({f.doc_url})"]
    if f.affected_resources:
        lines += ["", "**Affected resources:**"]
        for r in f.affected_resources:
            lines.append(f"- `{r}`")
    lines.append("")
    return "\n".join(lines)


def generate_markdown_report(
    result: AssessmentResult,
    comparison: Optional[dict] = None,
) -> str:
    """Return a full Markdown report string."""
    parts: list[str] = []

    # Header
    parts.append(f"# USX Migration Assessment Report")
    parts.append("")
    parts.append(f"**Workspace:** {result.workspace_name}  ")
    parts.append(f"**Subscription:** {result.subscription_id}  ")
    parts.append(f"**Timestamp:** {result.timestamp}  ")
    parts.append(f"**Readiness Score:** {result.readiness_score}%")
    parts.append("")

    # Summary counts
    parts.append("## Summary")
    parts.append("")
    parts.append(f"| Severity | Count |")
    parts.append(f"|----------|-------|")
    parts.append(f"| 🔴 Critical | {result.critical_count} |")
    parts.append(f"| ⚠️ Warning  | {result.warning_count} |")
    parts.append(f"| ℹ️ Info      | {result.info_count} |")
    parts.append(f"| ✅ OK        | {result.ok_count} |")
    parts.append("")

    # Comparison with previous run
    if comparison:
        parts.append("## Comparison with Previous Run")
        parts.append("")
        parts.append(f"**Delta:** {comparison.get('delta_summary', 'N/A')}")
        parts.append("")

        resolved = comparison.get("resolved_findings", [])
        new = comparison.get("new_findings", [])

        if resolved:
            parts.append(f"### ✅ Resolved ({len(resolved)})")
            parts.append("")
            for f in resolved:
                parts.append(f"- ~~{f.get('title', f.get('id', 'Unknown'))}~~")
            parts.append("")

        if new:
            parts.append(f"### 🆕 New ({len(new)})")
            parts.append("")
            for f in new:
                parts.append(f"- {f.get('title', f.get('id', 'Unknown'))}")
            parts.append("")

    # Findings by severity
    severity_order = [Severity.CRITICAL, Severity.WARNING, Severity.INFO, Severity.OK]
    for sev in severity_order:
        group = [f for f in result.findings if f.severity == sev]
        if not group:
            continue
        parts.append(f"## {_severity_section(sev)}")
        parts.append("")
        for f in group:
            parts.append(_finding_block(f))

    # Discovery errors
    if result.discovery_errors:
        parts.append("## Discovery Errors")
        parts.append("")
        parts.append("The following discovery steps encountered errors:")
        parts.append("")
        for step, err in result.discovery_errors.items():
            parts.append(f"- **{step}**: {err}")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by USX Migrator Assistant*")
    return "\n".join(parts)
